/* The memory information for each device is done in memory regions file.
 * The starting address and length of memory not defined in memory regions file are defined as 0. */

ATCM_PRV_START = DEFINED(ATCM_CR52_0_START) ? ATCM_CR52_0_START :
                 DEFINED(ATCM_CR52_1_START) ? ATCM_CR52_1_START : 0;
ATCM_PRV_LENGTH = DEFINED(ATCM_CR52_0_LENGTH) ? ATCM_CR52_0_LENGTH :
                  DEFINED(ATCM_CR52_1_LENGTH) ? ATCM_CR52_1_LENGTH : 0;
BTCM_PRV_START = DEFINED(BTCM_CR52_0_START) ? BTCM_CR52_0_START :
                 DEFINED(BTCM_CR52_1_START) ? BTCM_CR52_1_START : 0;
BTCM_PRV_LENGTH = DEFINED(BTCM_CR52_0_LENGTH) ? BTCM_CR52_0_LENGTH :
                  DEFINED(BTCM_CR52_1_LENGTH) ? BTCM_CR52_1_LENGTH : 0;

SYSTEM_RAM_PRV_START         = DEFINED(SYSTEM_RAM_START) ? SYSTEM_RAM_START : 0;
SYSTEM_RAM_PRV_LENGTH        = DEFINED(SYSTEM_RAM_LENGTH) ? SYSTEM_RAM_LENGTH : 0;
SYSTEM_RAM_MIRROR_PRV_START  = DEFINED(SYSTEM_RAM_MIRROR_START) ? SYSTEM_RAM_MIRROR_START : 0;
SYSTEM_RAM_MIRROR_PRV_LENGTH = DEFINED(SYSTEM_RAM_MIRROR_LENGTH) ? SYSTEM_RAM_MIRROR_LENGTH : 0;

xSPI0_CS0_SPACE_MIRROR_PRV_START  = DEFINED(xSPI0_CS0_SPACE_MIRROR_START) ? xSPI0_CS0_SPACE_MIRROR_START : 0;
xSPI0_CS0_SPACE_MIRROR_PRV_LENGTH = DEFINED(xSPI0_CS0_SPACE_MIRROR_LENGTH) ? xSPI0_CS0_SPACE_MIRROR_LENGTH : 0;
xSPI0_CS1_SPACE_MIRROR_PRV_START  = DEFINED(xSPI0_CS1_SPACE_MIRROR_START) ? xSPI0_CS1_SPACE_MIRROR_START : 0;
xSPI0_CS1_SPACE_MIRROR_PRV_LENGTH = DEFINED(xSPI0_CS1_SPACE_MIRROR_LENGTH) ? xSPI0_CS1_SPACE_MIRROR_LENGTH : 0;
xSPI1_CS0_SPACE_MIRROR_PRV_START  = DEFINED(xSPI1_CS0_SPACE_MIRROR_START) ? xSPI1_CS0_SPACE_MIRROR_START : 0;
xSPI1_CS0_SPACE_MIRROR_PRV_LENGTH = DEFINED(xSPI1_CS0_SPACE_MIRROR_LENGTH) ? xSPI1_CS0_SPACE_MIRROR_LENGTH : 0;
xSPI1_CS1_SPACE_MIRROR_PRV_START  = DEFINED(xSPI1_CS1_SPACE_MIRROR_START) ? xSPI1_CS1_SPACE_MIRROR_START : 0;
xSPI1_CS1_SPACE_MIRROR_PRV_LENGTH = DEFINED(xSPI1_CS1_SPACE_MIRROR_LENGTH) ? xSPI1_CS1_SPACE_MIRROR_LENGTH : 0;

CS0_SPACE_MIRROR_PRV_START  = DEFINED(CS0_SPACE_MIRROR_START) ? CS0_SPACE_MIRROR_START : 0;
CS0_SPACE_MIRROR_PRV_LENGTH = DEFINED(CS0_SPACE_MIRROR_LENGTH) ? CS0_SPACE_MIRROR_LENGTH : 0;
CS2_SPACE_MIRROR_PRV_START  = DEFINED(CS2_SPACE_MIRROR_START) ? CS2_SPACE_MIRROR_START : 0;
CS2_SPACE_MIRROR_PRV_LENGTH = DEFINED(CS2_SPACE_MIRROR_LENGTH) ? CS2_SPACE_MIRROR_LENGTH : 0;
CS3_SPACE_MIRROR_PRV_START  = DEFINED(CS3_SPACE_MIRROR_START) ? CS3_SPACE_MIRROR_START : 0;
CS3_SPACE_MIRROR_PRV_LENGTH = DEFINED(CS3_SPACE_MIRROR_LENGTH) ? CS3_SPACE_MIRROR_LENGTH : 0;
CS5_SPACE_MIRROR_PRV_START  = DEFINED(CS5_SPACE_MIRROR_START) ? CS5_SPACE_MIRROR_START : 0;
CS5_SPACE_MIRROR_PRV_LENGTH = DEFINED(CS5_SPACE_MIRROR_LENGTH) ? CS5_SPACE_MIRROR_LENGTH : 0;

xSPI0_CS0_SPACE_PRV_START  = DEFINED(xSPI0_CS0_SPACE_START) ? xSPI0_CS0_SPACE_START : 0;
xSPI0_CS0_SPACE_PRV_LENGTH = DEFINED(xSPI0_CS0_SPACE_LENGTH) ? xSPI0_CS0_SPACE_LENGTH : 0;
xSPI0_CS1_SPACE_PRV_START  = DEFINED(xSPI0_CS1_SPACE_START) ? xSPI0_CS1_SPACE_START : 0;
xSPI0_CS1_SPACE_PRV_LENGTH = DEFINED(xSPI0_CS1_SPACE_LENGTH) ? xSPI0_CS1_SPACE_LENGTH : 0;
xSPI1_CS0_SPACE_PRV_START  = DEFINED(xSPI1_CS0_SPACE_START) ? xSPI1_CS0_SPACE_START : 0;
xSPI1_CS0_SPACE_PRV_LENGTH = DEFINED(xSPI1_CS0_SPACE_LENGTH) ? xSPI1_CS0_SPACE_LENGTH : 0;
xSPI1_CS1_SPACE_PRV_START  = DEFINED(xSPI1_CS1_SPACE_START) ? xSPI1_CS1_SPACE_START : 0;
xSPI1_CS1_SPACE_PRV_LENGTH = DEFINED(xSPI1_CS1_SPACE_LENGTH) ? xSPI1_CS1_SPACE_LENGTH : 0;

CS0_SPACE_PRV_START  = DEFINED(CS0_SPACE_START) ? CS0_SPACE_START : 0;
CS0_SPACE_PRV_LENGTH = DEFINED(CS0_SPACE_LENGTH) ? CS0_SPACE_LENGTH : 0;
CS2_SPACE_PRV_START  = DEFINED(CS2_SPACE_START) ? CS2_SPACE_START : 0;
CS2_SPACE_PRV_LENGTH = DEFINED(CS2_SPACE_LENGTH) ? CS2_SPACE_LENGTH : 0;
CS3_SPACE_PRV_START  = DEFINED(CS3_SPACE_START) ? CS3_SPACE_START : 0;
CS3_SPACE_PRV_LENGTH = DEFINED(CS3_SPACE_LENGTH) ? CS3_SPACE_LENGTH : 0;
CS5_SPACE_PRV_START  = DEFINED(CS5_SPACE_START) ? CS5_SPACE_START : 0;
CS5_SPACE_PRV_LENGTH = DEFINED(CS5_SPACE_LENGTH) ? CS5_SPACE_LENGTH : 0;

PCIE0_MIRROR_PRV_START  = DEFINED(PCIE0_MIRROR_START) ? PCIE0_MIRROR_START : 0;
PCIE0_MIRROR_PRV_LENGTH = DEFINED(PCIE0_MIRROR_LENGTH) ? PCIE0_MIRROR_LENGTH : 0;
PCIE1_MIRROR_PRV_START  = DEFINED(PCIE1_MIRROR_START) ? PCIE1_MIRROR_START : 0;
PCIE1_MIRROR_PRV_LENGTH = DEFINED(PCIE1_MIRROR_LENGTH) ? PCIE1_MIRROR_LENGTH : 0;

DDR_MIRROR0_PRV_START = DEFINED(DDR_MIRROR0_CR52_0_START) ? DDR_MIRROR0_CR52_0_START :
                        DEFINED(DDR_MIRROR0_CR52_1_START) ? DDR_MIRROR0_CR52_1_START :
                        DEFINED(DDR_MIRROR0_CA55_0_START) ? DDR_MIRROR0_CA55_0_START :
                        DEFINED(DDR_MIRROR0_CA55_1_START) ? DDR_MIRROR0_CA55_1_START :
                        DEFINED(DDR_MIRROR0_CA55_2_START) ? DDR_MIRROR0_CA55_2_START :
                        DEFINED(DDR_MIRROR0_CA55_3_START) ? DDR_MIRROR0_CA55_3_START : 0;
DDR_MIRROR0_PRV_LENGTH = DEFINED(DDR_MIRROR0_CR52_0_LENGTH) ? DDR_MIRROR0_CR52_0_LENGTH :
                         DEFINED(DDR_MIRROR0_CR52_1_LENGTH) ? DDR_MIRROR0_CR52_1_LENGTH :
                         DEFINED(DDR_MIRROR0_CA55_0_LENGTH) ? DDR_MIRROR0_CA55_0_LENGTH :
                         DEFINED(DDR_MIRROR0_CA55_1_LENGTH) ? DDR_MIRROR0_CA55_1_LENGTH :
                         DEFINED(DDR_MIRROR0_CA55_2_LENGTH) ? DDR_MIRROR0_CA55_2_LENGTH :
                         DEFINED(DDR_MIRROR0_CA55_3_LENGTH) ? DDR_MIRROR0_CA55_3_LENGTH : 0;
DDR_MIRROR1_PRV_START = DEFINED(DDR_MIRROR1_CR52_0_START) ? DDR_MIRROR1_CR52_0_START :
                        DEFINED(DDR_MIRROR1_CR52_1_START) ? DDR_MIRROR1_CR52_1_START : 0;
DDR_MIRROR1_PRV_LENGTH = DEFINED(DDR_MIRROR1_CR52_0_LENGTH) ? DDR_MIRROR1_CR52_0_LENGTH :
                         DEFINED(DDR_MIRROR1_CR52_1_LENGTH) ? DDR_MIRROR1_CR52_1_LENGTH : 0;

DDR_PRV_START = DEFINED(DDR_CA55_0_START) ? DDR_CA55_0_START :
                DEFINED(DDR_CA55_1_START) ? DDR_CA55_1_START :
                DEFINED(DDR_CA55_2_START) ? DDR_CA55_2_START :
                DEFINED(DDR_CA55_3_LENGTH) ? DDR_CA55_3_LENGTH : 0;
DDR_PRV_LENGTH = DEFINED(DDR_CA55_0_LENGTH) ? DDR_CA55_0_LENGTH :
                 DEFINED(DDR_CA55_1_LENGTH) ? DDR_CA55_1_LENGTH :
                 DEFINED(DDR_CA55_2_LENGTH) ? DDR_CA55_2_LENGTH :
                 DEFINED(DDR_CA55_3_LENGTH) ? DDR_CA55_3_LENGTH : 0;

PCIE0_PRV_START = DEFINED(PCIE0_CA55_0_START) ? PCIE0_CA55_0_START :
                  DEFINED(PCIE0_CA55_1_START) ? PCIE0_CA55_1_START :
                  DEFINED(PCIE0_CA55_2_START) ? PCIE0_CA55_2_START :
                  DEFINED(PCIE0_CA55_3_START) ? PCIE0_CA55_3_START : 0;
PCIE0_PRV_LENGTH = DEFINED(PCIE0_CA55_0_LENGTH) ? PCIE0_CA55_0_LENGTH :
                   DEFINED(PCIE0_CA55_1_LENGTH) ? PCIE0_CA55_1_LENGTH :
                   DEFINED(PCIE0_CA55_2_LENGTH) ? PCIE0_CA55_2_LENGTH :
                   DEFINED(PCIE1_CA55_3_LENGTH) ? PCIE1_CA55_3_LENGTH : 0;
PCIE1_PRV_START = DEFINED(PCIE1_CA55_0_START) ? PCIE1_CA55_0_START :
                  DEFINED(PCIE1_CA55_1_START) ? PCIE1_CA55_1_START :
                  DEFINED(PCIE1_CA55_2_START) ? PCIE1_CA55_2_START :
                  DEFINED(PCIE1_CA55_3_START) ? PCIE1_CA55_3_START : 0;
PCIE1_PRV_LENGTH = DEFINED(PCIE1_CA55_0_LENGTH) ? PCIE1_CA55_0_LENGTH :
                   DEFINED(PCIE1_CA55_1_LENGTH) ? PCIE1_CA55_1_LENGTH :
                   DEFINED(PCIE1_CA55_2_LENGTH) ? PCIE1_CA55_2_LENGTH :
                   DEFINED(PCIE1_CA55_3_LENGTH) ? PCIE1_CA55_3_LENGTH : 0;

NONCACHE_PRV_START  = DEFINED(NONCACHE_START) ? NONCACHE_START : 0;
NONCACHE_PRV_LENGTH = DEFINED(NONCACHE_LENGTH) ? NONCACHE_LENGTH : 0;

SECONDARY_PRV = DEFINED(SECONDARY) ? SECONDARY : 0;
